    catch(Throwable e)
        {
            System.out.println("Exception: "+e);
        }
        finally{
            System.out.println("Exception Resolved");
        }